### ISSUE TITLE
_TypeError (Null check operator used on a null value)

### ISSUE THREAD

**Issue by jabguru** [Yukams/background_locator_fixed#100]
I get this error on both Android and iOS

<img width="940" alt="Screen Shot 2023-09-01 at 2 35 03 PM" src="https://github.com/Yukams/background_locator_fixed/assets/48110023/ac3bdf64-08b0-4cf6-abb6-0781018aef52">
<img width="938" alt="Screen Shot 2023-09-01 at 2 35 27 PM" src="https://github.com/Yukams/background_locator_fixed/assets/48110023/75253dd0-a779-4842-b2ef-d3fb46ee23e5">
<img width="964" alt="Screen Shot 2023-09-01 at 2 35 38 PM" src="https://github.com/Yukams/background_locator_fixed/assets/48110023/fec7745c-4179-4696-86e2-99cfa30dc90b">
<img width="957" alt="Screen Shot 2023-09-01 at 2 35 48 PM" src="https://github.com/Yukams/background_locator_fixed/assets/48110023/a938a745-171c-4e8c-8bc2-8c7aeeb7d7b3">
<img width="850" alt="Screen Shot 2023-09-01 at 2 35 59 PM" src="https://github.com/Yukams/background_locator_fixed/assets/48110023/d9bb51e5-7db0-48f4-ad38-96c35622abdf">

**Comment by Myzel394** [comment]
I had a similar issue with the `notificationTapCallback` argument. I had to add the `@pragma("vm:entry-point")` decorator. Can you send the full code for the `registerLocationUpdate` function?

**Comment by jabguru** [comment]
@Myzel394 thanks for your response

registerLocationUpdate is a method in the package.

**Comment by Myzel394** [comment]
> @Myzel394 thanks for your response
> 
> registerLocationUpdate is a method in the package.

I mean your code :D Can you send your code / how do you call this function?

**Comment by jabguru** [comment]
@Myzel394 that's what is in the first image, or should I resend the whole thing?

**Comment by Myzel394** [comment]
> @Myzel394 that's what is in the first image, or should I resend the whole thing?

yes please, just paste the content itself

**Comment by jabguru** [comment]
```
  Future<void> startLocationService() async {
    if (accountService.userCheck(userType: UserType.courier) &&
        currentScreenService.locationChangeLocationService == null) {
      //? calling this to get permission
      await locationService.getUserLocation();

      // TODO: THERE'S AN ERROR HERE
      await BackgroundLocator.registerLocationUpdate(
        updateLocationCallback,
        autoStop: false,
        iosSettings: const IOSSettings(
          accuracy: LocationAccuracy.NAVIGATION,
          distanceFilter: 200,
        ),
        androidSettings: AndroidSettings(
          accuracy: LocationAccuracy.NAVIGATION,
          interval: 5,
          distanceFilter: 200,
          androidNotificationSettings: AndroidNotificationSettings(
            notificationChannelName: 'Location tracking',
            notificationTitle: 'bg_location_notif_title'.tr(),
            notificationMsg: 'bg_location_notif_msg'.tr(),
            notificationBigMsg: 'bg_location_notif_big_msg'.tr(),
            notificationIconColor: kColorScheme.primaryColor,
            notificationIcon: 'notif_icon',
          ),
        ),
      );
    }
  }
```

@Myzel394

**Comment by Myzel394** [comment]
What does your `updateLocationCallback` look like?

**Comment by jabguru** [comment]
```
 Future<void> updateLocationCallback(LocationDto locationDto) async {
    await setupLocator(fromIsolate: true);

    if (accountService.userCheck(userType: UserType.courier) &&
        currentScreenService.locationChangeLocationService == null) {
      try {
        double lat = locationDto.latitude;
        double lng = locationDto.longitude;

        if (accountService.loggedInUser!.courier!.currentPositionLatitude !=
                lat ||
            accountService.loggedInUser!.courier!.currentPositionLongitude !=
                lng) {
          Map data = {
            'current_position_latitude': lat.toString(),
            'current_position_longitude': lng.toString(),
          };

          await accountRepository.updateCourier(data);
          log('Courier location updated: $lat, $lng');
        } else {
          log('Courier\'s position didn\'t change: $lat, $lng');
        }
      } catch (e) {
        log('Error updating courier location: $e');
      }
    }
  }

```

@Myzel394

**Comment by jabguru** [comment]
So I should just add the decorator
@pragma("vm:entry-point")
To the function?

@Myzel394

**Comment by Myzel394** [comment]
@jabguru yes exactly, sorry, I thought I wrote you an answer already but seems like I forgot to actually send the comment xD

**Comment by santojc** [comment]
@jabguru @Myzel394 whats the answer again? im blank here

**Comment by jabguru** [comment]
@santojc  its to add @pragma("vm:entry-point") ontop of your callback method.

I didn't have to do right now though, it's working on it's own again.

**Comment by jabguru** [comment]
I'll be closing the issue, it's working again.

**Comment by Myzel394** [comment]
@santojc it's exactly what @santojc said; it worked for me back then, but I don't know whether it will work now
