### ISSUE TITLE
Background locator crashing on Android 14

### ISSUE THREAD

**Issue by B3K4682** [Yukams/background_locator_fixed#137]
**Issue Description:**
We have been utilizing the **Background Locator 2** package in our application. While it functions correctly during testing in debug mode, we encounter persistent crashes when running the app in release mode, specifically on devices with Android 14. The crashes do not occur in debug mode, but they are consistent in release mode, impacting the app's stability.

Bug Report:
![BugReport](https://github.com/user-attachments/assets/e4dd057e-b0a6-45a0-8ab3-e062d7ccd207)

**Comment by QL-Uday** [comment]
There's an issue with type information of "TypeToken" being lost during the code shrinking process (like ProGuard or R8).

To resolve this, We need to add "-keep" statement for  "TypeToken" in "proguard-rules.pro" file.

Add the following in your "proguard-rules.pro" file.

`# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.`
`-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken`
`-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken`

**Comment by B3K4682** [comment]
We've tested it in **production** and it's working perfectly, Thank you!
