### ISSUE TITLE
Type mismatch: inferred type is String? but Any was expected

### ISSUE THREAD

**Issue by sandysultan** [Yukams/background_locator_fixed#15]
When building I got this error
![image](https://user-images.githubusercontent.com/5497458/179035649-27506fcf-c0f3-45ac-9343-ed08693f796a.png)

I got this fixed by changing Any to Any? in this codes below
LocationParserUtil.kt (11,74)
LocationParserUtil.kt (35,81)
LocationUpdateListener (6, 50)
IsolateHolderService (296, 59)

**Comment by Yukams** [comment]
I'll have a look next week, it's strange that no one reported this before though, maybe a new version of something broke it

**Comment by Yukams** [comment]
Hi @kirillwebmail, have you tried the fix proposed by @sandysultan ? If yes, and if it's working, could you provide a pull request ?

**Comment by sandysultan** [comment]
Hi @Yukams, please try this, I tested myself and worked
#22

**Comment by Yukams** [comment]
Thanks @sandysultan ! I will try this tonight and if everything is fine I'll push it to a pre-release branch and I'll post here again so you can retrieve the newest version with your fix :)

**Comment by Yukams** [comment]
Hi @kirillwebmail and @sandysultan, sorry it took a bit more time than I expected, but it's up on pub.dev as 2.0.6-dev.1
https://pub.dev/packages/background_locator_2/versions/2.0.6-dev.1

Thanks to both of you !

I'll merge this in the main branch next week if my tests are fine :)

**Comment by Yukams** [comment]
For anyone waiting for this fix to come to the main branch : I forgot to merge it before going for a week of vacation, just use the pre-release branch for now, sorry !

**Comment by al-bezd** [comment]
E/flutter (15453): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
E/flutter (15453): #0      SettingsUtil._getCommonArgumentsMap
package:background_locator_2/utils/settings_util.dart:39
E/flutter (15453): #1      SettingsUtil.getArgumentsMap
package:background_locator_2/utils/settings_util.dart:17
E/flutter (15453): #2      BackgroundLocator.registerLocationUpdate
package:background_locator_2/background_locator.dart:39
E/flutter (15453): #3      _MyAppState._startLocator
package:santurtrack/…/locator/example.dart:198
E/flutter (15453): #4      _MyAppState._onStart
package:santurtrack/…/locator/example.dart:160
E/flutter (15453): <asynchronous suspension>

PluginUtilities.getCallbackHandle(callback)!.toRawHandle()  this call error

in my code callback not null, but this expression falls into error, above

![image](https://user-images.githubusercontent.com/34810939/187638395-8dbc1e91-16c3-40e0-96cf-4d23ed8605ae.png)
![image](https://user-images.githubusercontent.com/34810939/187638481-2fac634c-4279-42ac-9ed1-8fea1b1f2648.png)

**Comment by srmanc** [comment]
@Yukams This PR can probably be merged to master now, correct? I'd like to include it in the next 2.0.6, please confirm.
