### ISSUE TITLE
IOS I want stop background service when app terminate by user is it possible with this amazing plugin ?

### ISSUE THREAD

**Issue by rajeshbdabhi** [Yukams/background_locator_fixed#16]
my application is currently live in play store and App Store. I want stop background service when app terminate by user. in background it is working fine. in android it is kill background service by adding **android:stopWithTask="true"** this and it is working fine. in iOS who can I do like this?

**Comment by Yukams** [comment]
Very nice, do you think you could push your branch and do a pull request so I can have a look and eventually push it to the main branch ?

**Comment by rajeshbdabhi** [comment]
I have send pull request please test and run it before marge.

**Comment by Yukams** [comment]
Alright I had a look at it and it seems like you've done a great job. 
I'll review it properly on Monday and I'll look to add it in the next update after testing. Thank you very much for your participation 🙏

**Comment by Yukams** [comment]
Hi @rajeshbdabhi, I've been testing the library a bit and I've stumbled across something weird. With version [2.0.4-dev.1](https://pub.dev/packages/background_locator_2/versions/2.0.4-dev.1), the example app on iOS is already stopping when killing the app. I suppose this is supposed to be a bug, but I can't tell if it's just me or not.
What version of the app were you using ?

**Comment by rajeshbdabhi** [comment]
I have tested in debug mode

**Comment by Yukams** [comment]
I've pushed your pull request to the new version 2.0.5. You should be able to use it now from the main branch :)

**Comment by rajeshbdabhi** [comment]
ok thanks

**Comment by oguzyildiz1991** [comment]
hi @rajeshbdabhi by terminating do you mean swiping up the app in the "recent apps" view, or do you mean just backgrounding the app? because it stops working for me if I terminate the app (if terminating means terminating it from the recent apps view)
