### ISSUE TITLE
not working for android

### ISSUE THREAD

**Issue by azaderdogan** [Yukams/background_locator_fixed#20]
ı toke this error
MainActivity.kt: (1, 9): Package name must be a '.'-separated identifier list #42519

**Comment by Yukams** [comment]
Hi @azaderdogan have you tried the test version 2.0.4-dev.1 ?

**Comment by azaderdogan** [comment]
> Hi @azaderdogan, ~have you tried the test version 2.0.4-dev.1 ?~ Can you try with the new version 2.0.5 ?

Thanks. work for me.

**Comment by Yukams** [comment]
Glad to hear it :)
