### ISSUE TITLE
initCallback doesnt call when start registerLocationUpdate

### ISSUE THREAD

**Issue by BaoNguyenSE** [Yukams/background_locator_fixed#23]
i try to print in function initCallback but nothing haapen.

**Comment by Yukams** [comment]
Hi @BaoNguyenSE, your problem occurs on Android or iOS ?

**Comment by BaoNguyenSE** [comment]
Hi @Yukams it occurs on Android. I dont check on IOS

**Comment by archsmilson** [comment]
It works fine for me on Android.

You need to share more information other than "it doesn't work", if you want anyone to help you.
 - do you get any errors?
 - does the Isolate service work normally, when you start the service (does isServiceRunning return true)?
 - share code snippets of you implementation - do you have the latest version?
 - did you set up everything correcty according to the [wiki](https://github.com/Yukams/background_locator_fixed/wik)?

**Comment by BaoNguyenSE** [comment]
Today i recheck, it work oke, function initCallback called, Thanks for help.
