### ISSUE TITLE
pod update failed 

### ISSUE THREAD

**Issue by kotran88** [Yukams/background_locator_fixed#29]
I'm trying example with my ios device. 

flutter build ios 

then cause error
 Error running pod install
```

Running pod install...                                             493ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `background_locator_2` from
    `.symlinks/plugins/background_locator_2/ios`
    [!] No podspec found for `background_locator_2` in
    `.symlinks/plugins/background_locator_2/ios`
```

I tried open with Runner.xcworkspace  
but cause error with below. 
I think I should pod install but keep failed
![스크린샷 2022-08-07 오전 10 26 00](https://user-images.githubusercontent.com/20656932/183271145-cad2141d-5597-402c-909f-aae84a1d11c0.png)

pedrojung@pedroui-MacBookPro ios % arch -arm64 pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] No podspec found for `background_locator_2` in `.symlinks/plugins/background_locator_2/ios`
pedrojung@pedroui-MacBookPro ios % arch -arm64 pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] No podspec found for `background_locator_2` in `.symlinks/plugins/background_locator_2/ios`
pedrojung@pedroui-MacBookPro ios % pod install
Analyzing dependencies
[!] No podspec found for `background_locator_2` in `.symlinks/plugins/background_locator_2/ios`
pedrojung@pedroui-MacBookPro ios %

**Comment by srmanc** [comment]
This PR fixes this issue: https://github.com/Yukams/background_locator_fixed/pull/37

**Comment by Yukams** [comment]
I'll update asap
