### ISSUE TITLE
Stop reporting while in Standby

### ISSUE THREAD

**Issue by JavierConde** [Yukams/background_locator_fixed#34]
First of all, excellent work of you in continuing with this project

Knowing that Android from version 10 has begun to change the way of working with location and communications, and in version 11 and 12 it is already a fact, I wanted to know if there is a way or if someone could solve, that when the cell phone is in standby mode, it is still reporting, since while it is like this, android lowers the communications and turns off the location, so that after a few hours it enables them for a few minutes and turns everything off again and stays like this until the cell phone is turned on for example and remains in the foreground, this is documented in android and it is its way of working, but I would like to know if there is a way to avoid this to always have a location in real time.

**Comment by Yukams** [comment]
Ah, I stumbled across the same problem as yours while working for a background application fetching user location periodically. I unfortunately never found a way to do so and felt like it was built in Android itself and wasn't something we could override somehow. As you said it's documented and I don't think there's anything we can do about it. I'm sorry ! Closing this issue.
