### ISSUE TITLE
Package not working in Production APK. but Working in Debug.

### ISSUE THREAD

**Issue by pruthvi1698** [Yukams/background_locator_fixed#38]
Error: 
E/flutter (14972): [ERROR:flutter/shell/common/shell.cc(93)] Dart Error: Dart_LookupLibrary: library 'package:tejumasala_sales/location_callback_handler.dart' not found.

**Comment by pruthvi1698** [comment]
I foundout this error can be solved by @pragma('vm:entry-point')
But dont know how. This error started from Flutter v3.3.0 and above. which roled out on 30th august

**Comment by yusriltakeuchi** [comment]
@pruthvi1698 can you show me an example where you put the @pragma('vm:entry-point') ?
I try this but not working

**Comment by pruthvi1698** [comment]
I saw some of the examples where they used @pragma('vm:entry-point') at in initial point of intent and background location initialisation.

This is the issue caused in 3.3.0. i downgraded the flutter version. will once upgrade and check if they have solved the issue.

**Comment by moovida** [comment]
Hi @pruthvi1698 , I just noticed that I kind of duplicated this in issue #50 . Could you try to add the pragma as I describe in the issue and see if it works for you. I was not able to solve it lie that.

**Comment by Yukams** [comment]
Fixed with version [2.0.6](https://pub.dev/packages/background_locator_2)
