### ISSUE TITLE
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/com.cis.zelderly-R4yzMHQbb02yUKGnof_ojg==/base.apk)

### ISSUE THREAD

**Issue by gopal-cis** [Yukams/background_locator_fixed#65]
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/com.cis.zelderly-R4yzMHQbb02yUKGnof_ojg==/base.apk)

After update location  implementation "com.google.android.gms:play-services-location:18.0.0" to  implementation "com.google.android.gms:play-services-location:21.0.1" It is giving some new issue

e: /Users/cis/flutter/.pub-cache/git/background_locator_fixed-10b10556223cbd477372f9ca2db8d39bbb44f0d1/android/src/main/kotlin/yukams/app/background_locator_2/provider/GoogleLocationProviderClient.kt: (34, 5): 'onLocationResult' overrides nothing

**Comment by tulioccalazans** [comment]
Hi, this is easy to fix!



Just replace it in background_locator_fixed\android\src\main\kotlin\yukams\app\background_locator_2\provider\GoogleLocationProviderClient.kt

```
private class LocationListener(val listener: LocationUpdateListener?) : LocationCallback() {
    override fun onLocationResult(location: LocationResult?) {
        listener?.onLocationUpdated(LocationParserUtil.getLocationMapFromLocation(location))
    }
}
```


To this

```
private class LocationListener(val listener: LocationUpdateListener?) : LocationCallback() {
    override fun onLocationResult(location: LocationResult) {
        listener?.onLocationUpdated(LocationParserUtil.getLocationMapFromLocation(location))
    }
}
```
(removing question mark)

**Comment by iamwaseemsh** [comment]
Having same issue app crashing, didn't work after apply above solution.
Using flutter version  3.7.3

Shutting down VM
E/AndroidRuntime(25956): FATAL EXCEPTION: main
E/AndroidRuntime(25956): Process: ais.rideshare.app, PID: 25956
E/AndroidRuntime(25956): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/ais.rideshare.app-fbyk0aXmt00c9AKcLWZ1LA==/base.apk)
E/AndroidRuntime(25956): 	at yukams.app.background_locator_2.provider.GoogleLocationProviderClient.requestLocationUpdates(GoogleLocationProviderClient.kt:17)
E/AndroidRuntime(25956): 	at yukams.app.background_locator_2.IsolateHolderService.startHolderService(IsolateHolderService.kt:199)
E/AndroidRuntime(25956): 	at yukams.app.background_locator_2.IsolateHolderService.onStartCommand(IsolateHolderService.kt:166)
E/AndroidRuntime(25956): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4407)
E/AndroidRuntime(25956): 	at android.app.ActivityThread.access$2100(ActivityThread.java:259)
E/AndroidRuntime(25956): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142)
E/AndroidRuntime(25956): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(25956): 	at android.os.Looper.loop(Looper.java:230)
E/AndroidRuntime(25956): 	at android.app.ActivityThread.main(ActivityThread.java:7873)
E/AndroidRuntime(25956): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25956): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
E/AndroidRuntime(25956): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by realkalash** [comment]
> Having same issue app crashing, didn't work after apply above solution. Using flutter version 3.7.3
> 
> Shutting down VM E/AndroidRuntime(25956): FATAL EXCEPTION: main E/AndroidRuntime(25956): Process: ais.rideshare.app, PID: 25956 E/AndroidRuntime(25956): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/ais.rideshare.app-fbyk0aXmt00c9AKcLWZ1LA==/base.apk) E/AndroidRuntime(25956): at yukams.app.background_locator_2.provider.GoogleLocationProviderClient.requestLocationUpdates(GoogleLocationProviderClient.kt:17) E/AndroidRuntime(25956): at yukams.app.background_locator_2.IsolateHolderService.startHolderService(IsolateHolderService.kt:199) E/AndroidRuntime(25956): at yukams.app.background_locator_2.IsolateHolderService.onStartCommand(IsolateHolderService.kt:166) E/AndroidRuntime(25956): at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4407) E/AndroidRuntime(25956): at android.app.ActivityThread.access$2100(ActivityThread.java:259) E/AndroidRuntime(25956): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2142) E/AndroidRuntime(25956): at android.os.Handler.dispatchMessage(Handler.java:107) E/AndroidRuntime(25956): at android.os.Looper.loop(Looper.java:230) E/AndroidRuntime(25956): at android.app.ActivityThread.main(ActivityThread.java:7873) E/AndroidRuntime(25956): at java.lang.reflect.Method.invoke(Native Method) E/AndroidRuntime(25956): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526) E/AndroidRuntime(25956): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

I had the same issue. I've found out that some other plugins use the new android "com.google.android.gms:play-services-location:21.0.1" plugin, so I had to found them and override them to the old versions.

In my case it was geolocator. Geolocator use geolocator_android and in the latest geolocator_android it use play-services-location:21.0.1.
This code in the pubspec.yaml fixed the issue for me:
```yaml
dependency_overrides:
  geolocator_android: 4.1.4
```

**Comment by Yukams** [comment]
Alright this seems to have been fixed with this PR https://github.com/Yukams/background_locator_fixed/pull/66. Closing this issue
