### ISSUE TITLE
Issue with compileSdkVersion 31

### ISSUE THREAD

**Issue by stingrayx** [Yukams/background_locator_fixed#7]
Hello Yukams,

thanks for managing this fork. I tried it today for the first time, but I'm getting an error when trying to start the Background Service.

The app is crashing and throwing an exception with following error message:

`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(23740): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(23740): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
E/AndroidRuntime(23740): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
E/AndroidRuntime(23740): 	at android.app.PendingIntent.getActivity(PendingIntent.java:451)
E/AndroidRuntime(23740): 	at android.app.PendingIntent.getActivity(PendingIntent.java:415)
E/AndroidRuntime(23740): 	at rekab.app.background_locator.IsolateHolderService.getNotification(IsolateHolderService.kt:116)
E/AndroidRuntime(23740): 	at rekab.app.background_locator.IsolateHolderService.onCreate(IsolateHolderService.kt:81)
E/AndroidRuntime(23740): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4940)
E/AndroidRuntime(23740): 	... 9 more
`

Could you look into this please?

Thanks

**Comment by Yukams** [comment]
Hi @stingrayx I've updated the branch with this pull request : https://github.com/Yukams/background_locator_fixed/pull/6
which should fix your error I believe, can you confirm ?

**Comment by stingrayx** [comment]
Hello,

Thanks I will test it on Wednesday!

Best regards

Valentin Tahon ***@***.***> schrieb am Mo., 27. Juni 2022,
11:43:

**Comment by stingrayx** [comment]
Works for me, thanks
